### ISSUE TITLE
npm run dev 出错

### ISSUE THREAD

**Issue by paiky** [XiangZi7/GlassMusicPlayer#1]
![image](https://user-images.githubusercontent.com/41196775/156503891-327c1e2e-bad1-47af-951e-e140d8a56e21.png)
![image](https://user-images.githubusercontent.com/41196775/156503904-ad7153ed-582d-461b-b0e7-e75f98f502d3.png)

是我拉取的姿势不对么

**Comment by 2658565123** [comment]
在项目根目录新建 .babelrc 文件
文件内容添加

`{
  "presets": [
    "stage-2"
  ]
}`

**Comment by 2658565123** [comment]
编译时另外一个异常

![image](https://user-images.githubusercontent.com/51154570/156915801-5fb9aa67-0510-498f-9b0e-7950a43f5904.png)

解决办法

1. 打开项目目录下的 build/webpack.dev.conf.js
2. 修改18行，将 `usePostCSS: true` 改为 `usePostCSS: false `

**Comment by paiky** [comment]
好的，不过是不是你提交我拉最新的下来好点 😄

**Comment by 2658565123** [comment]
> 好，不过不是你提交我最新的下来的好点😄

克隆吧
https://github.com/2658565123/glassesbeautifulgirl_code.git

**Comment by paiky** [comment]
谢谢作者大大！！！
