### ISSUE TITLE
修改网易云api

### ISSUE THREAD

**Issue by lsersc** [XiangZi7/GlassMusicPlayer#4]
大佬，要修改api为自建的是不是要修改 `.env.development里VITE_API_URL的值`？
还有就是`VITE_API_URL`和`VITE_API_AIURL`这两个有什么区别吗？因为我访问这两个域名都是网易云音乐api的页面。

**Comment by XiangZi7** [comment]
是的，需要修改.env.development里VITE_API_URL的值
