### ISSUE TITLE
二维码无法登录，显示

### ISSUE THREAD

**Issue by srebro-cn** [XiangZi7/GlassMusicPlayer#5]
![image](https://github.com/XiangZi7/KM-Music-Player/assets/53123002/48d7cec5-f6df-4599-a848-1430d2556760)

**Comment by srebro-cn** [comment]
docker run -it --name music --restart=unless-stopped -p 9999:3344 -d fooololo/km-music-player:latest
部署的脚本

**Comment by XiangZi7** [comment]
尝试科学上网、或者自己本地部署一个网易云接口
